export const STORAGE_KEY = 'face-value:structured-demo:v1';

export const persistedSealedTrial = {
  stage: 'analysis',
  selectedDrawerIndex: 0,
  selectedSpecimenId: 'registered-product-20260701120000000',
  assignedJob: 'Reduce visible redness',
  captureKind: 'followup',
  observation: 'review_due',
  placement: 'observation',
  placementSealed: false,
  comparison: 'comparable',
  confidence: 'possible',
  disturbance: 'none',
  baselineCapture: {
    id: 'baseline-e2e',
    kind: 'baseline',
    source: 'camera',
    mimeType: 'image/jpeg',
    createdAt: '2026-07-01T12:00:00.000Z',
    orientationRule: 'analysis-unmirrored',
  },
  followupCapture: {
    id: 'followup-e2e',
    kind: 'followup',
    source: 'camera',
    mimeType: 'image/jpeg',
    createdAt: '2026-07-15T12:00:00.000Z',
    orientationRule: 'analysis-unmirrored',
  },
  trace: null,
  analysis: {
    captureQuality: 'accepted',
    comparison: 'comparable',
    visibleSignal: 'visible redness',
    confidence: 'possible',
    finding: 'A small favorable shift showed up.',
    nonFinding: 'Visible redness moved in the intended direction.',
    relevantContext:
      'This prototype cannot yet tell whether the shift is larger than normal scan variation.',
    recommendedAction: 'wait',
    claimBoundary:
      'Possible directional evidence only. This does not establish product efficacy or clinical significance.',
    simulated: false,
    provider: 'youcam',
    baselineRawScore: 93.3356,
    followUpRawScore: 100,
    delta: 6.6644,
    direction: 'favorable',
    limitations: [
      'Prototype noise boundary has not been calibrated.',
    ],
  },
  record: null,
  archive: [],
  longitudinalEvidence: {
    protocol: {
      provider: 'youcam',
      apiVersion: '2.1',
      mode: 'hd',
      concern: 'hd_redness',
      region: null,
      scoreType: 'raw_score',
      captureProtocolVersion: 'face-value-youcam-1',
    },
    baseline: {
      provider: 'youcam',
      apiVersion: '2.1',
      mode: 'hd',
      concern: 'hd_redness',
      region: null,
      scoreType: 'raw_score',
      captureProtocolVersion: 'face-value-youcam-1',
      rawScore: 93.3356,
      capturedAt: '2026-07-01T12:00:00.000Z',
      captureQuality: 'accepted',
    },
    followUp: {
      provider: 'youcam',
      apiVersion: '2.1',
      mode: 'hd',
      concern: 'hd_redness',
      region: null,
      scoreType: 'raw_score',
      captureProtocolVersion: 'face-value-youcam-1',
      rawScore: 100,
      capturedAt: '2026-07-15T12:00:00.000Z',
      captureQuality: 'accepted',
    },
    comparison: {
      baselineRawScore: 93.3356,
      followUpRawScore: 100,
      delta: 6.6644,
      direction: 'favorable',
      calibration: 'pending',
      confidence: 'possible',
      limitations: [
        'Prototype noise boundary has not been calibrated.',
      ],
    },
  },
  registeredProduct: {
    id: 'registered-product-20260701120000000',
    accession: 'SPECIMEN 01',
    brand: 'Naturium',
    productName: 'Azelaic Topical Acid',
    strength: '10%',
    volume: '30 ml',
    assignedJob: 'Reduce visible redness',
    protocolId: 'youcam-redness-v1',
    createdAt: '2026-07-01T12:00:00.000Z',
  },
  baselineLockedAt: '2026-07-01T12:00:00.000Z',
  followUpEligibleAt: '2026-07-15T12:00:00.000Z',
  baselineContext: {
    makeup: false,
    recentHeatOrExercise: false,
    recentCleansingOrSkincare: false,
    routineOrTreatmentChange: false,
    note: null,
  },
  followUpContext: {
    makeup: false,
    recentHeatOrExercise: false,
    recentCleansingOrSkincare: false,
    routineOrTreatmentChange: false,
    note: null,
  },
  demoTimelineAdvanced: false,
  resultRevealed: false,
  oracleRevealState: 'sealed',
  oracleEvidenceDispensed: false,
  oracleCollectionStarted: false,
  oracleCommittedAt: null,
};
