from pathlib import Path

path = Path('/tmp/apply-trial-truth.mjs')
source = path.read_text()

BASE64_REPLACEMENTS = [('YWN0aXZlUmVkbmVzc0J1cnN0OiBudWxsLAphbm5vdW5jZW1lbnQ6IG9wdGlvbnMuc3ludGhldGljCg==', 'YWN0aXZlUmVkbmVzc0J1cnN0OiBudWxsLAogICAgYW5ub3VuY2VtZW50OiBvcHRpb25zLnN5bnRoZXRpYwo='),
 ('YWN0aXZlUmVkbmVzc0J1cnN0OiBudWxsLAp0cmlhbFRydXRoRXZpZGVuY2U6IHBlcnNpc3RlZC50cmlhbFRydXRoRXZpZGVuY2UsCnRyaWFsVHJ1dGhWYWxpZGF0aW9uOiBudWxsLAphbm5vdW5jZW1lbnQ6IG9wdGlvbnMuc3ludGhldGljCg==',
  'YWN0aXZlUmVkbmVzc0J1cnN0OiBudWxsLAogICAgdHJpYWxUcnV0aEV2aWRlbmNlOiBwZXJzaXN0ZWQudHJpYWxUcnV0aEV2aWRlbmNlLAogICAgdHJpYWxUcnV0aFZhbGlkYXRpb246IG51bGwsCiAgICBhbm5vdW5jZW1lbnQ6IG9wdGlvbnMuc3ludGhldGljCg=='),
 ('ewogIGlkOiAnY29tcGFyaXNvbl9wcm9jZXNzaW5nJywK', 'ewogICAgaWQ6ICdjb21wYXJpc29uX3Byb2Nlc3NpbmcnLAo='),
 ('ewogIGlkOiAndHJpYWxfdHJ1dGgnLAogIGxhYmVsOiAnVHJpYWwgdHJ1dGgnLAogIGRlc2NyaXB0aW9uOiAnT3BlbiB0aGUgcmVxdWlyZWQgZXZpZGVuY2UgY2hlY2twb2ludCBhZnRlciBmb2xsb3ctdXAgaXMgc2VjdXJlZC4nLAogIGZyZXF1ZW50OiBmYWxzZSwKfSwKewogIGlkOiAnY29tcGFyaXNvbl9wcm9jZXNzaW5nJywK',
  'ewogICAgaWQ6ICd0cmlhbF90cnV0aCcsCiAgICBsYWJlbDogJ1RyaWFsIHRydXRoJywKICAgIGRlc2NyaXB0aW9uOiAnT3BlbiB0aGUgcmVxdWlyZWQgZXZpZGVuY2UgY2hlY2twb2ludCBhZnRlciBmb2xsb3ctdXAgaXMgc2VjdXJlZC4nLAogICAgZnJlcXVlbnQ6IGZhbHNlLAogIH0sCiAgewogICAgaWQ6ICdjb21wYXJpc29uX3Byb2Nlc3NpbmcnLAo='),
 ('Y29uc3QgY2Fub25pY2FsS2V5ID0gY2Fub25pY2FsS2V5Rm9yRGVtb0ZpeHR1cmUocmVzdWx0Rml4dHVyZSk7CmNvbnN0IHNuYXBzaG90ID0gZXZhbHVhdGVSZWRuZXNzKHN0cnVjdHVyZWRDbG9uZShjYW5vbmljYWxSZWRuZXNzRml4dHVyZXNbY2Fub25pY2FsS2V5XSkpOwo=',
  'Y29uc3QgY2Fub25pY2FsS2V5ID0gY2Fub25pY2FsS2V5Rm9yRGVtb0ZpeHR1cmUocmVzdWx0Rml4dHVyZSk7CiAgY29uc3Qgc25hcHNob3QgPSBldmFsdWF0ZVJlZG5lc3Moc3RydWN0dXJlZENsb25lKGNhbm9uaWNhbFJlZG5lc3NGaXh0dXJlc1tjYW5vbmljYWxLZXldKSk7Cg=='),
 ('Y29uc3QgY2Fub25pY2FsS2V5ID0gY2Fub25pY2FsS2V5Rm9yRGVtb0ZpeHR1cmUocmVzdWx0Rml4dHVyZSk7CmNvbnN0IGZpeHR1cmVJbnB1dCA9IHN0cnVjdHVyZWRDbG9uZShjYW5vbmljYWxSZWRuZXNzRml4dHVyZXNbY2Fub25pY2FsS2V5XSk7CmlmIChyZXN1bHRGaXh0dXJlID09PSAnY29udHJhZGljdG9yeV9hbmNob3InKSB7CiAgZml4dHVyZUlucHV0LnBhdGllbnRBbmNob3IgPSB7CiAgICB2aXNpYmxlQ2hhbmdlOiAtMSwKICAgIHJlY29yZGVkQXQ6IGZpeHR1cmVJbnB1dC5ldmFsdWF0ZWRBdCwKICB9Owp9CmNvbnN0IHNuYXBzaG90ID0gZXZhbHVhdGVSZWRuZXNzKGZpeHR1cmVJbnB1dCk7Cg==',
  'Y29uc3QgY2Fub25pY2FsS2V5ID0gY2Fub25pY2FsS2V5Rm9yRGVtb0ZpeHR1cmUocmVzdWx0Rml4dHVyZSk7CiAgY29uc3QgZml4dHVyZUlucHV0ID0gc3RydWN0dXJlZENsb25lKGNhbm9uaWNhbFJlZG5lc3NGaXh0dXJlc1tjYW5vbmljYWxLZXldKTsKICBpZiAocmVzdWx0Rml4dHVyZSA9PT0gJ2NvbnRyYWRpY3RvcnlfYW5jaG9yJykgewogICAgZml4dHVyZUlucHV0LnBhdGllbnRBbmNob3IgPSB7CiAgICAgIHZpc2libGVDaGFuZ2U6IC0xLAogICAgICByZWNvcmRlZEF0OiBmaXh0dXJlSW5wdXQuZXZhbHVhdGVkQXQsCiAgICB9OwogIH0KICBjb25zdCBzbmFwc2hvdCA9IGV2YWx1YXRlUmVkbmVzcyhmaXh0dXJlSW5wdXQpOwo='),
 ('ICBvcmFjbGVDb21taXR0ZWRBdDogbnVsbCwKfTsKCnJldHVybiB7Cg==', 'ICAgIG9yYWNsZUNvbW1pdHRlZEF0OiBudWxsLAogIH07CgogIHJldHVybiB7Cg=='),
 ('ICBvcmFjbGVDb21taXR0ZWRBdDogbnVsbCwKICB0cmlhbFRydXRoRHJhZnQ6IHsKICAgIGFkaGVyZW5jZTogbnVsbCwKICAgIHRvbGVyYW5jZTogbnVsbCwKICAgIHN5bXB0b21zOiBbXSwKICAgIHZpc2libGVDaGFuZ2U6IG51bGwsCiAgfSwKICB0cmlhbFRydXRoRXZpZGVuY2UsCiAgdHJpYWxUcnV0aFZhbGlkYXRpb246IG51bGwsCn07CgpyZXR1cm4gewo=',
  'ICAgIG9yYWNsZUNvbW1pdHRlZEF0OiBudWxsLAogICAgdHJpYWxUcnV0aERyYWZ0OiB7CiAgICAgIGFkaGVyZW5jZTogbnVsbCwKICAgICAgdG9sZXJhbmNlOiBudWxsLAogICAgICBzeW1wdG9tczogW10sCiAgICAgIHZpc2libGVDaGFuZ2U6IG51bGwsCiAgICB9LAogICAgdHJpYWxUcnV0aEV2aWRlbmNlLAogICAgdHJpYWxUcnV0aFZhbGlkYXRpb246IG51bGwsCiAgfTsKCiAgcmV0dXJuIHsK'),
 ('cmV0dXJuIHsKICAuLi5jcmVhdGVkLAogIGRlbW9PcmlnaW5hdGVkOiB0cnVlLAogIGluY2x1ZGVzRmFjZUltYWdlOiBmYWxzZSwKfTsK',
  'cmV0dXJuIHsKICAgIC4uLmNyZWF0ZWQsCiAgICBkZW1vT3JpZ2luYXRlZDogdHJ1ZSwKICAgIGluY2x1ZGVzRmFjZUltYWdlOiBmYWxzZSwKICB9Owo='),
 ('Y29uc3QgZXZpZGVuY2UgPSBzdGF0ZS50cmlhbFRydXRoRXZpZGVuY2U7CnJldHVybiB7CiAgLi4uY3JlYXRlZCwKICBkZW1vT3JpZ2luYXRlZDogdHJ1ZSwKICBpbmNsdWRlc0ZhY2VJbWFnZTogZmFsc2UsCiAgdHJpYWxUcnV0aDogZXZpZGVuY2UgPz8gdW5kZWZpbmVkLAogIGFuY2hvclJlbGF0aW9uc2hpcDogZXZpZGVuY2UKICAgID8gYW5jaG9yUmVsYXRpb25zaGlwRm9yKHNuYXBzaG90LmVmZmVjdENsYXNzaWZpY2F0aW9uLCBldmlkZW5jZS5wYXRpZW50QW5jaG9yKQogICAgOiB1bmRlZmluZWQsCn07Cg==',
  'Y29uc3QgZXZpZGVuY2UgPSBzdGF0ZS50cmlhbFRydXRoRXZpZGVuY2U7CiAgcmV0dXJuIHsKICAgIC4uLmNyZWF0ZWQsCiAgICBkZW1vT3JpZ2luYXRlZDogdHJ1ZSwKICAgIGluY2x1ZGVzRmFjZUltYWdlOiBmYWxzZSwKICAgIHRyaWFsVHJ1dGg6IGV2aWRlbmNlID8/IHVuZGVmaW5lZCwKICAgIGFuY2hvclJlbGF0aW9uc2hpcDogZXZpZGVuY2UKICAgICAgPyBhbmNob3JSZWxhdGlvbnNoaXBGb3Ioc25hcHNob3QuZWZmZWN0Q2xhc3NpZmljYXRpb24sIGV2aWRlbmNlLnBhdGllbnRBbmNob3IpCiAgICAgIDogdW5kZWZpbmVkLAogIH07Cg=='),
 ('ewogIGlkOiAnYWRoZXJlbmNlJywKICBsYWJlbDogJ1Byb2R1Y3QgdXNlJywKICB2YWx1ZTogYWRoZXJlbmNlTGFiZWwoZXZhbHVhdGlvbi5hZGhlcmVuY2Uuc3RhdHVzKSwKICBjYW5vbmljYWxWYWx1ZTogZXZhbHVhdGlvbi5hZGhlcmVuY2Uuc3RhdHVzLAp9LAp7CiAgaWQ6ICdtaXNzaW5nLWV2aWRlbmNlJywK',
  'ICAgICAgICAgIHsKICAgICAgICAgICAgaWQ6ICdhZGhlcmVuY2UnLAogICAgICAgICAgICBsYWJlbDogJ1Byb2R1Y3QgdXNlJywKICAgICAgICAgICAgdmFsdWU6IGFkaGVyZW5jZUxhYmVsKGV2YWx1YXRpb24uYWRoZXJlbmNlLnN0YXR1cyksCiAgICAgICAgICAgIGNhbm9uaWNhbFZhbHVlOiBldmFsdWF0aW9uLmFkaGVyZW5jZS5zdGF0dXMsCiAgICAgICAgICB9LAogICAgICAgICAgewogICAgICAgICAgICBpZDogJ21pc3NpbmctZXZpZGVuY2UnLAo='),
 ('ewogIGlkOiAnYWRoZXJlbmNlJywKICBsYWJlbDogJ1Byb2R1Y3QgdXNlJywKICB2YWx1ZTogYWRoZXJlbmNlTGFiZWwoZXZhbHVhdGlvbi5hZGhlcmVuY2Uuc3RhdHVzKSwKICBjYW5vbmljYWxWYWx1ZTogZXZhbHVhdGlvbi5hZGhlcmVuY2Uuc3RhdHVzLAp9LAp7CiAgaWQ6ICd0b2xlcmFuY2Utc2V2ZXJpdHknLAogIGxhYmVsOiAnU2tpbiByZXNwb25zZScsCiAgdmFsdWU6IHRvbGVyYW5jZUxhYmVsKHJlY29yZC50cmlhbFRydXRoKSwKICBjYW5vbmljYWxWYWx1ZTogcmVjb3JkLnRyaWFsVHJ1dGg/LnRvbGVyYW5jZS5zZXZlcml0eSA/PyAnbm90X2NvbGxlY3RlZCcsCn0sCnsKICBpZDogJ3JlcG9ydGVkLXN5bXB0b21zJywKICBsYWJlbDogJ1JlcG9ydGVkIHN5bXB0b21zJywKICB2YWx1ZTogc3ltcHRvbUxhYmVsKHJlY29yZC50cmlhbFRydXRoKSwKfSwKewogIGlkOiAncGFydGljaXBhbnQtb2JzZXJ2YXRpb24nLAogIGxhYmVsOiAnUGFydGljaXBhbnQgb2JzZXJ2YXRpb24nLAogIHZhbHVlOiBwYXJ0aWNpcGFudE9ic2VydmF0aW9uTGFiZWwocmVjb3JkLnRyaWFsVHJ1dGgpLAp9LAp7CiAgaWQ6ICdwYXJ0aWNpcGFudC1yZXBvcnQtdGltZXN0YW1wJywKICBsYWJlbDogJ1BhcnRpY2lwYW50IHJlcG9ydCB0aW1lc3RhbXAnLAogIHZhbHVlOiByZWNvcmQudHJpYWxUcnV0aAogICAgPyBzYXZlZFRpbWVzdGFtcChyZWNvcmQudHJpYWxUcnV0aC5yZWNvcmRlZEF0KQogICAgOiAnTm90IGNvbGxlY3RlZCcsCiAgY2Fub25pY2FsVmFsdWU6IHJlY29yZC50cmlhbFRydXRoPy5yZWNvcmRlZEF0ID8/ICdub3RfY29sbGVjdGVkJywKfSwKewogIGlkOiAnYW5jaG9yLXJlbGF0aW9uc2hpcCcsCiAgbGFiZWw6ICdBbmNob3IgcmVsYXRpb25zaGlwJywKICB2YWx1ZTogYW5jaG9yUmVsYXRpb25zaGlwTGFiZWwocmVjb3JkKSwKICBjYW5vbmljYWxWYWx1ZTogcmVjb3JkLmFuY2hvclJlbGF0aW9uc2hpcCA/PyAnbm90X2NvbGxlY3RlZCcsCn0sCnsKICBpZDogJ21pc3NpbmctZXZpZGVuY2UnLAo=',
  'ICAgICAgICAgIHsKICAgICAgICAgICAgaWQ6ICdhZGhlcmVuY2UnLAogICAgICAgICAgICBsYWJlbDogJ1Byb2R1Y3QgdXNlJywKICAgICAgICAgICAgdmFsdWU6IGFkaGVyZW5jZUxhYmVsKHJlY29yZC50cmlhbFRydXRoPy5hZGhlcmVuY2Uuc3RhdHVzID8/ICd1bmtub3duJyksCiAgICAgICAgICAgIGNhbm9uaWNhbFZhbHVlOiByZWNvcmQudHJpYWxUcnV0aD8uYWRoZXJlbmNlLnN0YXR1cyA/PyAnbm90X2NvbGxlY3RlZCcsCiAgICAgICAgICB9LAogICAgICAgICAgewogICAgICAgICAgICBpZDogJ3RvbGVyYW5jZS1zZXZlcml0eScsCiAgICAgICAgICAgIGxhYmVsOiAnU2tpbiByZXNwb25zZScsCiAgICAgICAgICAgIHZhbHVlOiB0b2xlcmFuY2VMYWJlbChyZWNvcmQudHJpYWxUcnV0aCksCiAgICAgICAgICAgIGNhbm9uaWNhbFZhbHVlOiByZWNvcmQudHJpYWxUcnV0aD8udG9sZXJhbmNlLnNldmVyaXR5ID8/ICdub3RfY29sbGVjdGVkJywKICAgICAgICAgIH0sCiAgICAgICAgICB7CiAgICAgICAgICAgIGlkOiAncmVwb3J0ZWQtc3ltcHRvbXMnLAogICAgICAgICAgICBsYWJlbDogJ1JlcG9ydGVkIHN5bXB0b21zJywKICAgICAgICAgICAgdmFsdWU6IHN5bXB0b21MYWJlbChyZWNvcmQudHJpYWxUcnV0aCksCiAgICAgICAgICB9LAogICAgICAgICAgewogICAgICAgICAgICBpZDogJ3BhcnRpY2lwYW50LW9ic2VydmF0aW9uJywKICAgICAgICAgICAgbGFiZWw6ICdQYXJ0aWNpcGFudCBvYnNlcnZhdGlvbicsCiAgICAgICAgICAgIHZhbHVlOiBwYXJ0aWNpcGFudE9ic2VydmF0aW9uTGFiZWwocmVjb3JkLnRyaWFsVHJ1dGgpLAogICAgICAgICAgfSwKICAgICAgICAgIHsKICAgICAgICAgICAgaWQ6ICdwYXJ0aWNpcGFudC1yZXBvcnQtdGltZXN0YW1wJywKICAgICAgICAgICAgbGFiZWw6ICdQYXJ0aWNpcGFudCByZXBvcnQgdGltZXN0YW1wJywKICAgICAgICAgICAgdmFsdWU6IHJlY29yZC50cmlhbFRydXRoCiAgICAgICAgICAgICAgPyBzYXZlZFRpbWVzdGFtcChyZWNvcmQudHJpYWxUcnV0aC5yZWNvcmRlZEF0KQogICAgICAgICAgICAgIDogJ05vdCBjb2xsZWN0ZWQnLAogICAgICAgICAgICBjYW5vbmljYWxWYWx1ZTogcmVjb3JkLnRyaWFsVHJ1dGg/LnJlY29yZGVkQXQgPz8gJ25vdF9jb2xsZWN0ZWQnLAogICAgICAgICAgfSwKICAgICAgICAgIHsKICAgICAgICAgICAgaWQ6ICdhbmNob3ItcmVsYXRpb25zaGlwJywKICAgICAgICAgICAgbGFiZWw6ICdBbmNob3IgcmVsYXRpb25zaGlwJywKICAgICAgICAgICAgdmFsdWU6IGFuY2hvclJlbGF0aW9uc2hpcExhYmVsKHJlY29yZCksCiAgICAgICAgICAgIGNhbm9uaWNhbFZhbHVlOiByZWNvcmQuYW5jaG9yUmVsYXRpb25zaGlwID8/ICdub3RfY29sbGVjdGVkJywKICAgICAgICAgIH0sCiAgICAgICAgICB7CiAgICAgICAgICAgIGlkOiAnbWlzc2luZy1ldmlkZW5jZScsCg=='),
 ('ICAnY2Fub25pY2FsUmVkbmVzc0ZpeHR1cmVzJywKXSkgewo=', 'ICAgICAgJ2Nhbm9uaWNhbFJlZG5lc3NGaXh0dXJlcycsCiAgICBdKSB7Cg=='),
 ('ICAnY2Fub25pY2FsUmVkbmVzc0ZpeHR1cmVzJywKICAnc2FmZXR5X2ludGVycnVwdGlvbicsCiAgJ3JldHJ5X2Fsb25lJywKICAnbm90X3Byb3Zpbmdfam9iJywKXSkgewo=',
  'ICAgICAgJ2Nhbm9uaWNhbFJlZG5lc3NGaXh0dXJlcycsCiAgICAgICdzYWZldHlfaW50ZXJydXB0aW9uJywKICAgICAgJ3JldHJ5X2Fsb25lJywKICAgICAgJ25vdF9wcm92aW5nX2pvYicsCiAgICBdKSB7Cg==')]

for old, new in BASE64_REPLACEMENTS:
    source = source.replace(old, new)

source = source.replace(
    "  const first = source.indexOf(oldValue);\n  const last = source.lastIndexOf(oldValue);",
    "  if (path === 'src/features/demo-lab/demoFixtureState.ts' && oldValue === 'state: PhaseBFaceValueState') {\n"
    "    const replaced = source.replace(/state: PhaseBFaceValueState(?=[,)])/g, newValue);\n"
    "    if (replaced === source) replacementErrors.push(`Missing function parameter replacement in ${path}`);\n"
    "    else await writeFile(path, replaced);\n"
    "    continue;\n"
    "  }\n"
    "  if (path === 'src/features/demo-lab/demoFixtureState.ts' && oldValue === '): PhaseBFaceValueState {') {\n"
    "    await writeFile(path, source.split(oldValue).join(newValue));\n"
    "    continue;\n"
    "  }\n"
    "  const first = source.indexOf(oldValue);\n"
    "  const last = source.lastIndexOf(oldValue);",
)
source = source.replace(
    'for (const [path, oldEncoded, newEncoded] of replacements) {',
    'const replacementErrors = [];\nfor (const [path, oldEncoded, newEncoded] of replacements) {',
)
source = source.replace(
    "  if (first < 0) throw new Error(`Missing exact replacement in ${path}: ${oldValue.slice(0, 100)}`);",
    "  if (first < 0) { replacementErrors.push(`Missing exact replacement in ${path}: ${oldValue.slice(0, 100)}`); continue; }",
)
source = source.replace(
    "  if (first !== last) throw new Error(`Ambiguous exact replacement in ${path}: ${oldValue.slice(0, 100)}`);",
    "  if (first !== last) { replacementErrors.push(`Ambiguous exact replacement in ${path}: ${oldValue.slice(0, 100)}`); continue; }",
)
source += "\nif (replacementErrors.length > 0) throw new Error(replacementErrors.join('\\n'));\n"
path.write_text(source)
